id: P004145
initial_creation_type: ocr
source_metadata:
  id: bdr:W30528
  title: སྨན་ཡིག་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    c5f006e26e0945de8c42ceedfa22e449:
      image_group_id: I1KG14753
      title: ''
      volume_number: 1
      total_pages: 770
      base_file: v001.txt
